# Generated by Django 5.2.17 on 2026-09-21 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('customer_company', models.CharField(db_index=True, max_length=255)),
                ('location_town', models.CharField(blank=True, default='', max_length=100)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_type', models.CharField(blank=True, default='', max_length=100)),
                ('product_service', models.CharField(blank=True, default='', max_length=255)),
                ('requirement_specifications', models.TextField(blank=True, default='')),
                ('estimated_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('estimated_value_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_discussion_feedback', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_status', models.CharField(default='PENDING', max_length=50)),
                ('sales_stage', models.CharField(default='New Lead', max_length=100)),
                ('probability_pct', models.IntegerField(default=0)),
                ('quotation_no', models.CharField(blank=True, default='', max_length=100)),
                ('quotation_value_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sample_trial_status', models.CharField(blank=True, default='', max_length=100)),
                ('actual_order_value_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reason_lost', models.CharField(blank=True, default='', max_length=255)),
                ('remarks_management_notes', models.TextField(blank=True, default='')),
                ('competitor_won_by', models.CharField(blank=True, default='', max_length=100)),
                ('stage_last_updated', models.DateField(auto_now=True)),
                ('corrective_action', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DropdownLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_services', models.JSONField(default=list)),
                ('customer_types', models.JSONField(default=list)),
                ('sales_stages', models.JSONField(default=list)),
                ('departments', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(default='Sales', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Salespersons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('area_route_visited', models.CharField(blank=True, default='', max_length=150)),
                ('customer_company', models.CharField(db_index=True, max_length=255)),
                ('specific_location', models.CharField(blank=True, default='', max_length=255)),
                ('prospect_status', models.CharField(default='Existing', max_length=50)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('product_service', models.CharField(blank=True, default='', max_length=255)),
                ('activity_type', models.CharField(default='Physical Visit', max_length=100)),
                ('requirement_estimated_volume', models.CharField(blank=True, default='', max_length=100)),
                ('discussion_outcome', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('quotation_submitted_value_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order_received_value_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_collected_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('market_competitor_intelligence', models.TextField(blank=True, default='')),
                ('management_support_needed', models.TextField(blank=True, default='')),
                ('responsible_person_dept', models.CharField(blank=True, default='', max_length=100)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('issue_status', models.CharField(default='Pending', max_length=50)),
                ('customer_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='marketing.customerpipeline')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_activities', to='marketing.salesperson')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='customerpipeline',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_deals', to='marketing.salesperson'),
        ),
    ]
