# Generated by Django 5.2.17 on 2026-10-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_link_approved_sales_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpipeline',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
