# Generated by Django 5.2.17 on 2026-10-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_customerpipeline_email_dailyactivity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpipeline',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
